{% set name = "rapidgzip" %}
{% set version = "0.10.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rapidgzip-{{ version }}.tar.gz
  sha256: 7535504f1ce08c7014ba8580dbe6ac308e60d9f216bc7125e3a6dd4c803102f8
  patches:
    - configure-dependencies.patch

build:
  entry_points:
    - rapidgzip=rapidgzip:cli
  script_env:
    - RAPIDGZIP_BUILD_CXXOPTS=system
    - RAPIDGZIP_BUILD_ISAL=disabled
    - RAPIDGZIP_BUILD_RPMALLOC=enabled
    - RAPIDGZIP_BUILD_ZLIB=system
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - sysroot_linux-64 2.17  # [linux64]
    - nasm
    - cxxopts>=3,<4
    - zlib>=1.2.3,<2
  host:
    - libcxx {{ cxx_compiler_version }}  # [osx]
    - python
    - setuptools >=46.4.0
    - wheel
    - cython >=0.29.24
    - pip
    - cxxopts>=3,<4
    - zlib>=1.2.3,<2
  run:
    - {{ pin_compatible("libcxx", max_pin=None) }}  # [osx]
    - python
    - cxxopts>=3,<4
    - zlib>=1.2.3,<2

test:
  imports:
    - rapidgzip
  commands:
    - pip check
    - rapidgzip --help
  requires:
    - pip

about:
  home: https://github.com/mxmlnkn/rapidgzip
  summary: Parallel random access to gzip files
  license: BSD-3-Clause AND Unlicense AND BSD-2-Clause AND Apache-2.0 AND MIT
  license_file:
    - LICENSE-APACHE
    - LICENSE-MIT
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - ap--
    - mxmlnkn
